#!/bin/bash

v_a=0.00277
v_p=-0.00086141

v_x=`echo $v_a - $v_p | bc`
v_y=`echo -$v_a - $v_p | bc`
v_z=`echo $v_p + $v_p | bc`


counter=0
for i in {0..31415}
do
#	for j in {0..100}
#	do

		theta=0.6154
		phi=1
		r=1
		vr=0.00000000000001;


#		r2=`python -c "print "$r`
#		vr2=`python -c "print "$vr"*"$i`
#		theta2=`python -c "print "$theta`
#			phi2=`python -c "print "$phi`

		theta2=`python -c "print "$theta`
		phi2=`python -c "print "$phi`
		r2=`python -c "print "$r`
		vr2=`python -c "print "$r`




#		echo $v_x $v_y $v_z

#		`./main ${v_x} ${v_y} ${v_z} ${counter}>> /mnt/hgfs/outdata/matlab/new/test${counter}.txt`
#good with normal coordinates
#		`./main ${v_x} ${v_y} ${v_z} ${counter} /mnt/hgfs/outdata/matlab/quick/test${counter}.txt`

#		`./main ${r2} ${vr2} ${theta2} ${phi2} ${counter} /mnt/hgfs/outdata/matlab/spherical/test${counter}.txt`

		`./main ${r2} ${vr2} ${phi2} ${theta2} ${counter} /mnt/hgfs/outdata/matlab/spherical2/test${counter}.txt`

		counter=$[$counter+1]
#	done
done




